name: Build & Push | Dockerhub

on:
  push:
    tags:
      - v*


jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
  
    steps:
      - name: Create SHA Container Tag
        id: sha_tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "tag=$tag" >> $GITHUB_ENV
          echo "version=${GITHUB_REF#refs/v*/}" >> $GITHUB_ENV
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+rc[0-9]+$ ]]
          then  
              echo "beta=true" >> $GITHUB_ENV
          else
              echo "beta=false" >> $GITHUB_ENV
          fi
          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: ${{ env.beta }} == 'false'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: ${{ env.beta }} == 'false'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          tags: |
            mayankfawkes/filesync:latest
            mayankfawkes/filesync:${{ env.version }}
          build-args: |
            git_sha=${{ env.tag }}
            app_version=${{ env.version }}
      
      - name: Build and push
        if: ${{ env.beta }} == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          tags: |
            mayankfawkes/filesync:${{ env.version }}
          build-args: |
            git_sha=${{ env.tag }}
            app_version=${{ env.version }}