name: Build & Push | Dockerhub

on:
  push:
    tags:
      - v*


jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
  
    steps:
      - name: Create SHA Container Tag
        id: sha_tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "tag=$tag" >> $GITHUB_ENV
          echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          file: ./Dockerfile
          tags: |
            mayankfawkes/filesync:latest
            mayankfawkes/filesync:${{ env.version }}
          build-args: |
            git_sha=${{ env.tag }}
            app_version=${{ env.version }}
